import ScrollToTop from "@/components/scroll-to-top";
import PortfolioContainer from "@/containers/global/portfolio";
import IntroContainer from "@/containers/home/intro";
import Layout from "@/layouts";
import Footer from "@/layouts/footer";
import Header from "@/layouts/header";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>Hello Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="wrapper home-default-wrapper">
          <Header />
          <IntroContainer />
          <main className="main-content">
            <h1>Hello Portfolio</h1>
            <PortfolioContainer />
          </main>
          <Footer />
          <ScrollToTop />
        </div>
      </Layout>
    </>
  );
}
