import Head from "next/head";

import { Button } from "reactstrap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className="container">
          <h1>Hello Portfolio</h1>
          <Button>Button</Button>
        </main>
        <footer></footer>
      </div>
    </>
  );
}
